### ISSUE TITLE
Microsoft Onedrive v2 not working

### ISSUE THREAD

**Issue by energywave** [adrianoamalfi/hassos-addons#17]
**Describe the bug**
No backup destination is working (not only Microsoft OneDrive v2)

**To Reproduce**
1. Create a new backup
2. In destination step select "Microsoft OneDrive v2"
3. Follow instructions
4. Click on "Connection test" button. The error shown in the screenshot is showing.

**Expected behavior**
Should work normally as a standalone installation.

**Screenshots**
My config:
![image](https://user-images.githubusercontent.com/2051567/211157329-b414427b-3357-4fb1-bc43-2dc258817edb.png)
The error:
![image](https://user-images.githubusercontent.com/2051567/211157054-4d7d320d-08c3-42f6-861e-ec10079812a1.png)

**Desktop (please complete the following information):**
 - Home Assistant 2023.1.1
 - This addon 0.1.7
 - HassOS on RPI 4 4GB 64bit

**Additional context**
- I've tried to use "\" and "/" for path (in Windows I'm using backslash but maybe here we're on linux so I've tried slashes too). Same result.
- I'm using Duplicati on my Windows servers and clients and the OneDrive v2 function to work requires, on Windows, Microsoft Visual C runtime 2015-2022. Maybe on linux it requires some other dependency that is not included in this addon? Just my 2 cents.
- I've tested even Google Drive, Dropbox, FTP and SFTP. None of them are working. Dropbox are blaming a malformed OAuth 2 data, the other all Internal Server Error.
- Actually there isn't a working option :(
- Could be related maybe to the ARM architecture...?
- Seems to not log anything when Internal Error arise.

If you have ideas on what to test, check or change please tell me. I hope this AddOn will be working for all the people!

**Comment by adrianoamalfi** [comment]
Hi @energywave , tested now with Onedrive (and webdav) from my RPI4 and everythings worked for me!
Could be related maybe to destination folder? Spaces in the path are ok but the **destination folder on onedrive must exist**


<img width="512" alt="image" src="https://user-images.githubusercontent.com/1764444/211161280-cdc821a0-f4b4-4237-b8d7-4b0d7ee08bca.png">

<img width="297" alt="image" src="https://user-images.githubusercontent.com/1764444/211161359-5b13dccd-f802-4aa2-b4df-e3b6950f1d93.png">

<img width="333" alt="image" src="https://user-images.githubusercontent.com/1764444/211161368-dc8729f7-6156-436e-b84f-1981b72f67ce.png">

**Comment by energywave** [comment]
Hello and thank you to have tested. The destination doesn't have to exists, when you press test button it should warn you asking to create the folder (recursively).
I'm pretty sure of that as I configured this week  7 windows different hosts this way.
Furthermore same result using all other destinations mentioned (Internal Server Error without nothing in the log).
Have you tested with HassOS 32 or 64 bit? I'm on 64. There should be a difference somewhere...

Please reopen the issue, it's not resolved at all.

**Comment by adrianoamalfi** [comment]
> Hello and thank you to have tested. The destination doesn't have to exists, when you press test button it should warn you asking to create the folder (recursively). I'm pretty sure of that as I configured this week 7 windows different hosts this way. Furthermore same result using all other destinations mentioned (Internal Server Error without nothing in the log). Have you tested with HassOS 32 or 64 bit? I'm on 64. There should be a difference somewhere...
> 
> Please reopen the issue, it's not resolved at all.

no log in Duplicati Log (about > show log)?

**Comment by energywave** [comment]
Absolutely no log in About > Show log. No trace of activity in "real time" mode nor in "archived" mode. When it generates an Internal Server Error no log is stored.
The strange thing is that exact same behavior with nearly every destination options (I listed them above), even the simplest FTP and SFTP (Internal Server Error without logs).
No log even in the Home Assistant add-on registry page.

I've updated your add-on to 0.1.8, no improvements.

I managed to work only with one destination only: Alternative FTP. Using that destination I could use a local NAS to backup my HA.
But we have to resolve that.
I'm on RPI4 x64, just to refresh that. What are you using on your RPI4? 32 or 64 bits?

**Comment by energywave** [comment]
I further tried to analyze the problem using Chrome developer tools to see what's going on during the request.
I then see that pressin "Connection test" button the following POST is done on this path `/api/v1/remoteoperation/test`.
The reply is a HTTP 500 Internal Server Error with the folloing body:
```
{
  "Error": "missing-folder"
}
```
But I ensure you that this "missing folder" is not the problem at all (furthermore it's not shown in the UI where you see only "Internal Server Error".

Whatever I set in the path (I've tried all permutations of slashes, backslashes, with/without the first one and the last one. I've tried path without spaces, existing and non existing) the result is the same. With FTP, OneDrive v2 and other destinations.
If I test on a Windows Machine the exact same parameters no problems at all.

**Comment by adrianoamalfi** [comment]
Hi @energywave, have you done further tests? still not working for you?

**Comment by energywave** [comment]
Sorry, I had no time to do tests yet. I'll do that but I cannot guarantee when.
Be assured that when I'll do some test and especially if I'll discover something I'll update this issue.
I really hope that we can fix that for the whole Home Assistant community!
I have been in contact on mastodon with Frenck that did a try some years ago but abandoned and I asked why:
![Screenshot_2023-01-28-23-46-51-69.jpg](https://user-images.githubusercontent.com/2051567/215294556-de5f2919-066e-4150-b959-03f38b687485.jpg)

**Comment by energywave** [comment]
After having installed the just released last version 2.0.7.2_canary_2023-05-25 the UI was not working. Any listbox was not populated so nothing worked.
I forced an update CTRL+F5 and the UI started again to work.
I tested OneDrive v2 destination and... now it works!!!

Thank you Adriano for your work.
